# Generated by Django 4.2.5 on 2023-09-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_case_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='user',
            new_name='username',
        ),
    ]
