# Generated by Django 4.2.5 on 2023-09-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_case_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.FileField(upload_to='project/photos/input'),
        ),
    ]
