# Generated by Django 4.2.5 on 2023-09-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_case_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Past Cases'},
        ),
    ]
